id: A88F68FBE
title: The Single-Form Daily Practice from Chimé Pakmé Nyingtik (The Heart Essence
  of the Sublime Lady of Immortality)
type: translation
pechas:
- I05884138
- I4CA9112E
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:37:35.229435
  last_modified_at: 2023-01-04 12:37:35.229441
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I05884138/52BE: EE46
  I4CA9112E/6784: EE46
